apiVersion: v1
kind: Service
metadata:
  name: wings
  labels:
    app.kubernetes.io/name: wings
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wings.animaniacs.farh.net
    service.cilium.io/forwarding-mode: dsr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 2022
      targetPort: sftp
      name: sftp
    - port: 25565
      targetPort: 25565
      name: p25565
    - port: 25566
      targetPort: 25566
      name: p25566
    - port: 25567
      targetPort: 25567
      name: p25567
    - port: 25568
      targetPort: 25568
      name: p25568
    - port: 25569
      targetPort: 25569
      name: p25569
    - port: 25570
      targetPort: 25570
      name: p25570
    - port: 25571
      targetPort: 25571
      name: p25571
    - port: 25572
      targetPort: 25572
      name: p25572
    - port: 25573
      targetPort: 25573
      name: p25573
    - port: 25574
      targetPort: 25574
      name: p25574
    - port: 25575
      targetPort: 25575
      name: p25575
  selector:
    app.kubernetes.io/name: wings
