apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-jexpanel-db-pw.yaml
  - secret-jexpanel-userdatadb-pw.yaml
  - mariadb-jexpanel-db.yaml
  - mariadb-jexpanel-userdatadb.yaml
  - database-jexpanel-panel.yaml
  - user-jexpanel.yaml
  - grant-jexpanel-db.yaml
