apiVersion: v1
kind: ConfigMap
metadata:
  name: picolimbo
data:
  server.toml: |
    bind = "0.0.0.0:25565"
    [server_list]
    max_players = 12
    message_of_the_day = "farh.net Minecraft Server"
    [forwarding]
    method = "MODERN"
    secret = "${VELOCITY_FWD_SECRET}"
    [world]
    spawn_position = [0.0, 320.0, 0.0]
    spawn_rotation = [0.0, 0.0]
    dimension = "end"
    time = "day"
