apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volumes.yaml
  - configmap-paper-velocity.yaml
  - configmap-picolimbo.yaml
  - deployment-picolimbo.yaml
  - service-picolimbo.yaml
  - deployment-filebrowser.yaml
  - service-filebrowser.yaml
  - ingress-filebrowser.yaml
  - helmrelease-mc-lobby.yaml
  - helmrelease-mc-cursed-walking.yaml
  - helmrelease-mc-detroit.yaml
  - helmrelease-mc-rochester.yaml
  - helmrelease-mc-rlcraft.yaml
  - helmrelease-mc-bmc-4.yaml
  - helmrelease-mc-bmc-5.yaml
  - helmrelease-mc-atm-8.yaml
  - helmrelease-mc-atm-9.yaml
  - helmrelease-mc-atm-10.yaml
  - helmrelease-mc-prominence-2.yaml
  - helmrelease-mc-mmc-5.yaml
