apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease-mc-rlcraft.yaml
  - helmrelease-mc-bmc-4.yaml
  - helmrelease-mc-bmc-5.yaml
  - helmrelease-mc-atm-10.yaml
  - helmrelease-mc-prom-ii.yaml
