apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-pterodactyl-db-pw.yaml
  - mariadb-pterodactyl-db.yaml
  - database-panel.yaml
  - user-pterodactyl.yaml
  - grant-pterodactyl-panel.yaml
