apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-pterodactyl-db-pw.yaml
  - mariadb-pterodactyl.yaml
  - database-main.yaml
  - user-pterodactyl.yaml
  - grant-pterodactyl.yaml
