apiVersion: v1
kind: ConfigMap
metadata:
  name: panel
  labels:
    app: panel
data:
  APP_URL: "https://${PTERODACTYL_PANEL_FQDN}"
  APP_TIMEZONE: ${PTERODACTYL_PANEL_TIMEZONE}
  APP_SERVICE_AUTHOR: "${PTERODACTYL_PANEL_EMAIL}"
  MAIL_FROM: ${PTERODACTYL_PANEL_EMAIL}
  MAIL_DRIVER: "smtp"
  MAIL_HOST: "${PTERODACTYL_PANEL_MAIL_HOST}"
  MAIL_PORT: "587"
  MAIL_USERNAME: ${PTERODACTYL_PANEL_MAIL_USER}
  MAIL_ENCRYPTION: "tls"
  APP_ENV: "production"
  APP_ENVIRONMENT_ONLY: "false"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "database"
  QUEUE_DRIVER: "database"
  DB_HOST: "pterodactyl-db-primary"
  DB_PORT: "3306"
  DB_DATABASE: "panel"
  DB_USERNAME: "pterodactyl"
  ADMIN_EMAIL: "${PTERODACTYL_ADMIN_EMAIL}"
  ADMIN_USER: "${PTERODACTYL_ADMIN_USER}"
  ADMIN_FIRST: "${PTERODACTYL_ADMIN_FIRST}"
  ADMIN_LAST: "${PTERODACTYL_ADMIN_LAST}"
  #RECAPTCHA_ENABLED: "false". # Sometimes useful to disable for testing in an automated way
