apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik-external
  tls:
  - hosts:
    - ${PTERODACTYL_PANEL_FQDN}
    secretName: panel-tls
  rules:
  - host: ${PTERODACTYL_PANEL_FQDN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: panel
            port:
              number: 80
