apiVersion: v1
kind: ConfigMap
metadata:
  name: ctrlpanelgg
  labels:
    app: ctrlpanelgg
data:
  APP_URL: "https://${CTRLPANELGG_PANEL_FQDN}"
  TRUSTED_PROXIES: "*"
  APP_TIMEZONE: ${CTRLPANELGG_PANEL_TIMEZONE}
  APP_SERVICE_AUTHOR: "${CTRLPANELGG_PANEL_EMAIL}"
  MAIL_FROM: ${CTRLPANELGG_PANEL_EMAIL}
  MAIL_DRIVER: "smtp"
  MAIL_HOST: "${CTRLPANELGG_PANEL_MAIL_HOST}"
  MAIL_PORT: "587"
  MAIL_USERNAME: ${CTRLPANELGG_PANEL_MAIL_USER}
  MAIL_ENCRYPTION: "tls"
  APP_ENV: "production"
  APP_ENVIRONMENT_ONLY: "false"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "database"
  QUEUE_DRIVER: "database"
  DB_HOST: "pterodactyl-db-primary"
  DB_PORT: "3306"
  DB_DATABASE: "ctrlpanelgg"
  DB_USERNAME: "ctrlpanelgg"
  ADMIN_EMAIL: "${CTRLPANELGG_ADMIN_EMAIL}"
  ADMIN_USER: "${CTRLPANELGG_ADMIN_USER}"
  ADMIN_FIRST: "${CTRLPANELGG_ADMIN_FIRST}"
  ADMIN_LAST: "${CTRLPANELGG_ADMIN_LAST}"
  #RECAPTCHA_ENABLED: "false". # Sometimes useful to disable for testing in an automated way
