apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset-prominence-ii.yaml
  - service-prominence-ii.yaml
  - statefulset-atm10.yaml
  - service-atm10.yaml
  - statefulset-bmc4.yaml
  - service-bmc4.yaml
  - statefulset-bmc5.yaml
  - service-bmc5.yaml
