apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - service-prominence-ii.yaml
  - statefulset-bmc4.yaml
  - statefulset-bmc5.yaml
 - statefulset-prominence-ii.yaml
 - statefulset-atm10.yaml
